"""Init

Revision ID: bd56c29c5e19
Revises: c5bb122d824b
Create Date: 2023-02-01 13:58:00.618950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd56c29c5e19'
down_revision = 'c5bb122d824b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
